//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Time_Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_info
    {
        public string ID_EMP { get; set; }
        public string FIRSTNAME_EMP { get; set; }
        public string LASTNAME_EMP { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string POSITION { get; set; }
        public string SECTION { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> TERMINATED_DATE { get; set; }
        public string ADDRESS_EMP { get; set; }
        public string path_image { get; set; }
    }
}
