//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Time_Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday_emp
    {
        public string HOLIDAY_ID { get; set; }
        public string ID_EMP { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public string MODE_HOLIDAY { get; set; }
        public string TYPE_HOLIDAY { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
    }
}
