//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Time_Attendance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Time_AttendanceEntities : DbContext
    {
        public Time_AttendanceEntities()
            : base("name=Time_AttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_info> Employee_info { get; set; }
        public virtual DbSet<Holiday_emp> Holiday_emp { get; set; }
        public virtual DbSet<Leave_employee> Leave_employee { get; set; }
        public virtual DbSet<OT_EMP> OT_EMP { get; set; }
        public virtual DbSet<Timesheet_emp> Timesheet_emp { get; set; }
        public virtual DbSet<Transac_login> Transac_login { get; set; }
        public virtual DbSet<User_Authen> User_Authen { get; set; }
    
        public virtual int Insert_employee_info(string id_emp, string firstname_emp, string lastname_emp, Nullable<System.DateTime> dOB, string email, string mobile_phone, string position, string section, Nullable<System.DateTime> effective_date, Nullable<System.DateTime> terminated_date, string address_emp, string path_image)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var firstname_empParameter = firstname_emp != null ?
                new ObjectParameter("Firstname_emp", firstname_emp) :
                new ObjectParameter("Firstname_emp", typeof(string));
    
            var lastname_empParameter = lastname_emp != null ?
                new ObjectParameter("Lastname_emp", lastname_emp) :
                new ObjectParameter("Lastname_emp", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobile_phoneParameter = mobile_phone != null ?
                new ObjectParameter("Mobile_phone", mobile_phone) :
                new ObjectParameter("Mobile_phone", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("Section", section) :
                new ObjectParameter("Section", typeof(string));
    
            var effective_dateParameter = effective_date.HasValue ?
                new ObjectParameter("Effective_date", effective_date) :
                new ObjectParameter("Effective_date", typeof(System.DateTime));
    
            var terminated_dateParameter = terminated_date.HasValue ?
                new ObjectParameter("Terminated_date", terminated_date) :
                new ObjectParameter("Terminated_date", typeof(System.DateTime));
    
            var address_empParameter = address_emp != null ?
                new ObjectParameter("Address_emp", address_emp) :
                new ObjectParameter("Address_emp", typeof(string));
    
            var path_imageParameter = path_image != null ?
                new ObjectParameter("Path_image", path_image) :
                new ObjectParameter("Path_image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_employee_info", id_empParameter, firstname_empParameter, lastname_empParameter, dOBParameter, emailParameter, mobile_phoneParameter, positionParameter, sectionParameter, effective_dateParameter, terminated_dateParameter, address_empParameter, path_imageParameter);
        }
    
        public virtual int Insert_leave_emp(string id_emp, Nullable<double> total_vacation, Nullable<double> balance_vacation, Nullable<double> total_sick, Nullable<double> balance_sick, Nullable<double> total_private_leave, Nullable<double> balance_private_leave)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var total_vacationParameter = total_vacation.HasValue ?
                new ObjectParameter("Total_vacation", total_vacation) :
                new ObjectParameter("Total_vacation", typeof(double));
    
            var balance_vacationParameter = balance_vacation.HasValue ?
                new ObjectParameter("Balance_vacation", balance_vacation) :
                new ObjectParameter("Balance_vacation", typeof(double));
    
            var total_sickParameter = total_sick.HasValue ?
                new ObjectParameter("Total_sick", total_sick) :
                new ObjectParameter("Total_sick", typeof(double));
    
            var balance_sickParameter = balance_sick.HasValue ?
                new ObjectParameter("Balance_sick", balance_sick) :
                new ObjectParameter("Balance_sick", typeof(double));
    
            var total_private_leaveParameter = total_private_leave.HasValue ?
                new ObjectParameter("Total_private_leave", total_private_leave) :
                new ObjectParameter("Total_private_leave", typeof(double));
    
            var balance_private_leaveParameter = balance_private_leave.HasValue ?
                new ObjectParameter("Balance_private_leave", balance_private_leave) :
                new ObjectParameter("Balance_private_leave", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_leave_emp", id_empParameter, total_vacationParameter, balance_vacationParameter, total_sickParameter, balance_sickParameter, total_private_leaveParameter, balance_private_leaveParameter);
        }
    
        public virtual int Insert_login(string login_id, string id_emp, Nullable<System.DateTime> datetime_login)
        {
            var login_idParameter = login_id != null ?
                new ObjectParameter("Login_id", login_id) :
                new ObjectParameter("Login_id", typeof(string));
    
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var datetime_loginParameter = datetime_login.HasValue ?
                new ObjectParameter("Datetime_login", datetime_login) :
                new ObjectParameter("Datetime_login", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_login", login_idParameter, id_empParameter, datetime_loginParameter);
        }
    
        public virtual int Insert_OT(string oT_id, string id_emp, Nullable<System.TimeSpan> oT_time_from, Nullable<System.TimeSpan> oT_time_to, Nullable<System.DateTime> date_OT)
        {
            var oT_idParameter = oT_id != null ?
                new ObjectParameter("OT_id", oT_id) :
                new ObjectParameter("OT_id", typeof(string));
    
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var oT_time_fromParameter = oT_time_from.HasValue ?
                new ObjectParameter("OT_time_from", oT_time_from) :
                new ObjectParameter("OT_time_from", typeof(System.TimeSpan));
    
            var oT_time_toParameter = oT_time_to.HasValue ?
                new ObjectParameter("OT_time_to", oT_time_to) :
                new ObjectParameter("OT_time_to", typeof(System.TimeSpan));
    
            var date_OTParameter = date_OT.HasValue ?
                new ObjectParameter("Date_OT", date_OT) :
                new ObjectParameter("Date_OT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_OT", oT_idParameter, id_empParameter, oT_time_fromParameter, oT_time_toParameter, date_OTParameter);
        }
    
        public virtual int Insert_scanin(string logtime_id, string id_emp, Nullable<System.TimeSpan> time_scanin, Nullable<System.DateTime> date_scan)
        {
            var logtime_idParameter = logtime_id != null ?
                new ObjectParameter("Logtime_id", logtime_id) :
                new ObjectParameter("Logtime_id", typeof(string));
    
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var time_scaninParameter = time_scanin.HasValue ?
                new ObjectParameter("Time_scanin", time_scanin) :
                new ObjectParameter("Time_scanin", typeof(System.TimeSpan));
    
            var date_scanParameter = date_scan.HasValue ?
                new ObjectParameter("Date_scan", date_scan) :
                new ObjectParameter("Date_scan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_scanin", logtime_idParameter, id_empParameter, time_scaninParameter, date_scanParameter);
        }
    
        public virtual int Insert_scanout(string logtime_id, string id_emp, Nullable<System.TimeSpan> time_scanout, Nullable<System.DateTime> date_scan)
        {
            var logtime_idParameter = logtime_id != null ?
                new ObjectParameter("Logtime_id", logtime_id) :
                new ObjectParameter("Logtime_id", typeof(string));
    
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var time_scanoutParameter = time_scanout.HasValue ?
                new ObjectParameter("Time_scanout", time_scanout) :
                new ObjectParameter("Time_scanout", typeof(System.TimeSpan));
    
            var date_scanParameter = date_scan.HasValue ?
                new ObjectParameter("Date_scan", date_scan) :
                new ObjectParameter("Date_scan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_scanout", logtime_idParameter, id_empParameter, time_scanoutParameter, date_scanParameter);
        }
    
        public virtual int Update_leave_emp(string id_emp, Nullable<double> balance_vacation, Nullable<double> balance_sick, Nullable<double> balance_private_leave)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var balance_vacationParameter = balance_vacation.HasValue ?
                new ObjectParameter("Balance_vacation", balance_vacation) :
                new ObjectParameter("Balance_vacation", typeof(double));
    
            var balance_sickParameter = balance_sick.HasValue ?
                new ObjectParameter("Balance_sick", balance_sick) :
                new ObjectParameter("Balance_sick", typeof(double));
    
            var balance_private_leaveParameter = balance_private_leave.HasValue ?
                new ObjectParameter("Balance_private_leave", balance_private_leave) :
                new ObjectParameter("Balance_private_leave", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_leave_emp", id_empParameter, balance_vacationParameter, balance_sickParameter, balance_private_leaveParameter);
        }
    
        public virtual ObjectResult<View_EmpInfo_Result1> View_EmpInfo(string id_emp, string firstname_emp, string lastname_emp)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            var firstname_empParameter = firstname_emp != null ?
                new ObjectParameter("Firstname_emp", firstname_emp) :
                new ObjectParameter("Firstname_emp", typeof(string));
    
            var lastname_empParameter = lastname_emp != null ?
                new ObjectParameter("Lastname_emp", lastname_emp) :
                new ObjectParameter("Lastname_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_EmpInfo_Result1>("View_EmpInfo", id_empParameter, firstname_empParameter, lastname_empParameter);
        }
    
        public virtual ObjectResult<View_leave_emp_Result> View_leave_emp(string id_emp)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_leave_emp_Result>("View_leave_emp", id_empParameter);
        }
    
        public virtual ObjectResult<View_leaveInfo_Result> View_leaveInfo(string id_emp)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_leaveInfo_Result>("View_leaveInfo", id_empParameter);
        }
    
        public virtual ObjectResult<View_OT_emp_Result> View_OT_emp(string id_emp)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_OT_emp_Result>("View_OT_emp", id_empParameter);
        }
    
        public virtual ObjectResult<View_timesheet_Result> View_timesheet(string id_emp)
        {
            var id_empParameter = id_emp != null ?
                new ObjectParameter("Id_emp", id_emp) :
                new ObjectParameter("Id_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_timesheet_Result>("View_timesheet", id_empParameter);
        }
    
        public virtual int Insert_authen_User(string iD_EMP, string pASSWORD_ENCRYPT, string rESULT_KEY)
        {
            var iD_EMPParameter = iD_EMP != null ?
                new ObjectParameter("ID_EMP", iD_EMP) :
                new ObjectParameter("ID_EMP", typeof(string));
    
            var pASSWORD_ENCRYPTParameter = pASSWORD_ENCRYPT != null ?
                new ObjectParameter("PASSWORD_ENCRYPT", pASSWORD_ENCRYPT) :
                new ObjectParameter("PASSWORD_ENCRYPT", typeof(string));
    
            var rESULT_KEYParameter = rESULT_KEY != null ?
                new ObjectParameter("RESULT_KEY", rESULT_KEY) :
                new ObjectParameter("RESULT_KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_authen_User", iD_EMPParameter, pASSWORD_ENCRYPTParameter, rESULT_KEYParameter);
        }
    }
}
